apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: "jc-itau"
        metrics_path: "/actuator/prometheus"
        static_configs:
          - targets: ["spring-app-service"]
            labels:
              application: "api-jwt-decode"
