name: CD com Docker

on:
  workflow_dispatch:
    inputs:
      java:
        description: 'Java version to use'
        required: true
        default: '21'
        options:
          - '21'
          - '22'
      branch:
        description: 'Branch or tag to use'
        required: true
        default: 'main'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up JDK ${{ github.event.inputs.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ github.event.inputs.java }}
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: ./mvnw -B verify

      - name: Build Docker image
        run: docker build -f Dockerfile -t $(grep "image:" manifest/spring-deploy.yaml | sed 's/.*image://g') .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push $(grep "image:" manifest/spring-deploy.yaml | sed 's/.*image://g')

      - name: Install OpenShift CLI
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
          tar xvzf openshift-client-linux.tar.gz
          sudo mv oc /usr/local/bin/

      - name: Login to OpenShift
        run: |
          oc login ${{ secrets.OPENSHIFT_SERVER_URL }} --token=${{ secrets.OPENSHIFT_TOKEN }}

      - name: Apply specific manifests
        run: |
          oc apply -f manifest/spring-deploy.yaml